### ISSUE TITLE
doesn't use AWS production code/library?

### ISSUE THREAD

**Issue by klausbadelt** [awslabs/statelint#19]
While I appreciate this offer, for [dev/prod parity](https://12factor.net/dev-prod-parity) reasons this tool should really use the same code and libraries AWS uses in production. Even as "pre-check" or even more as test, a separate implementation mimicking something else is flawed by definition.

**Comment by timbray** [comment]
That would be difficult, since statelint is written in Ruby, and the Step Functions service isn't. Ruby is an appropriate choice for something run ad hoc from the command line; the trade-offs for an AWS service are different.

Amazon States Language is not tied to any one language or execution environment, by design.

**Comment by klausbadelt** [comment]
Thanks for your explanation. 

As AWS StepFunctions seems the reference implementation I will probably prefer using the awscli (temporary creating a state machine for testing/linting) though.
