### ISSUE TITLE
Any plan to port lib to nodejs / npm module?

### ISSUE THREAD

**Issue by mikelax** [awslabs/statelint#4]
Given the high usage of the js / nodejs SDK and libs, is there any possibility of porting this from a ruby gem to npm module? 

That would make it easier to include in nodejs based projects.

**Comment by timbray** [comment]
Excellent idea!

**Comment by jezhiggins** [comment]
We have a node package that runs ASL state machines, [statebox](https://www.npmjs.com/package/@wmfs/statebox,) and I've just taken a couple of days to port j2119 and statelint to javascript too - [npm package](https://www.npmjs.com/package/@wmfs/statelint), [repository](https://www.github.com/wmfs/statelint).

I've only just finished this up - I believe it to be correct, but don't be surprised if we slip out a point release or two over the next few days.

Thanks Tim!

**Comment by jezhiggins** [comment]
Turned out to be a point release or six (and there will, no doubt, be more over time) but if you would like to sling some attention, that would be lovely and we'd be very grateful. 

We have a blogpost about the release at https://tymly.io/blog/announcing-statelint/ which you could point to if you wished.

Thanks for making your code available. The validator itself and working on the port has been extremely helpful in understanding ASL better. Now I'm off to try and resolve the deviations from spec in statebox.

**Comment by timbray** [comment]
https://twitter.com/timbray/status/1055170080722407424

**Comment by wong-a** [comment]
Linking to the JavaScript port previously mentioned:
* https://github.com/wmfs/statelint
* https://github.com/wmfs/tymly-statelint


At the moment, we don't have concrete plans to publish another validator in JavaScript. If there is enough interest, we may consider providing a validator interface over the functionality in [aws/amazon-states-language-service](https://github.com/aws/amazon-states-language-service) which is responsible for the ASL linting capabilities in [aws-toolkit-vscode](https://github.com/aws/aws-toolkit-vscode).
